const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const DATA_FILE = path.join(ROOT, 'data', 'games.json');

const SEO_FILE = path.join(ROOT, 'data', 'seo.json');

// optional per-page rewrite suggestions (generated by QA)
const SUGGEST_FILE = path.join(ROOT, 'scripts', 'qa', 'rewrite-suggestions.json');
let rewriteSuggestions = null;
if (fs.existsSync(SUGGEST_FILE)) {
  try { rewriteSuggestions = JSON.parse(fs.readFileSync(SUGGEST_FILE,'utf8')); } catch(e){ console.warn('failed to parse rewrite-suggestions.json', e); }
}
if (!fs.existsSync(DATA_FILE)) {
  console.error('data/games.json not found');
  process.exit(1);
}

const games = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));

function joinUrl(base, rel){
  if(!base) return rel || '';
  if(!rel) return base.replace(/\/+$/,'') + '/';
  return base.replace(/\/+$/,'') + '/' + String(rel).replace(/^\/+/, '');
}

function ensureDir(dir){ if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true }); }

ensureDir(DIST);

// Use the SPA template so per-game paths render the same inline player view on refresh.
const TEMPLATE_PATH = path.join(ROOT, 'game-template.html');
let templateHtml = null;
if (fs.existsSync(TEMPLATE_PATH)) {
  templateHtml = fs.readFileSync(TEMPLATE_PATH, 'utf8');
} else {
  console.warn('game-template.html not found — falling back to simple per-game pages');
}

let seo = null;
if (fs.existsSync(SEO_FILE)) {
  try { seo = JSON.parse(fs.readFileSync(SEO_FILE,'utf8')); } catch(e){ console.warn('failed to parse seo.json', e); }
}
// read optional site data for homepage
const SITE_DATA_PATH = path.join(ROOT, 'data', 'site.json');
let site = null;
if (fs.existsSync(SITE_DATA_PATH)) {
  try { site = JSON.parse(fs.readFileSync(SITE_DATA_PATH,'utf8')); } catch(e){ console.warn('failed to parse site.json', e); }
}

// load generated image manifest (image-pipeline writes this)
const IMG_MANIFEST_PATH = path.join(ROOT, 'assets', 'games', 'img', 'manifest.json');
let imgManifest = {};
if (fs.existsSync(IMG_MANIFEST_PATH)){
  try{ imgManifest = JSON.parse(fs.readFileSync(IMG_MANIFEST_PATH,'utf8')); }catch(e){ console.warn('failed to parse image manifest', e); }
}

// helper: render responsive picture markup using manifest when available
function renderResponsivePicture(imgPath, alt, w, h, siteRoot){
  if (!imgPath) return '';
  const normalized = imgPath.replace(/^\/+/, '');
  const manifestEntry = imgManifest[normalized];
  const sizesAttr = `(max-width:600px) 100vw, ${w}px`;
  if (manifestEntry && Array.isArray(manifestEntry.variants) && manifestEntry.variants.length){
    // group by format
    const byFormat = {};
    manifestEntry.variants.forEach(v=>{ byFormat[v.format] = byFormat[v.format] || []; byFormat[v.format].push(v); });
    let out = '<picture>';
    ['avif','webp'].forEach(fmt=>{
      if (byFormat[fmt]){
        const srcset = byFormat[fmt].map(v=> `${joinUrl(siteRoot, v.path)} ${v.width}w`).join(', ');
        const type = fmt==='avif' ? 'image/avif' : 'image/webp';
        out += `<source type="${type}" srcset="${srcset}" sizes="${sizesAttr}">`;
      }
    });
    // pick largest available original-like variant for img src fallback
    const fallback = manifestEntry.variants.slice().sort((a,b)=>b.width-a.width)[0];
    const primary = fallback ? joinUrl(siteRoot, fallback.path) : joinUrl(siteRoot, normalized);
    const imgSrcset = manifestEntry.variants.map(v=> `${joinUrl(siteRoot, v.path)} ${v.width}w`).join(', ');
    out += `<img src="${primary}" srcset="${imgSrcset}" sizes="${sizesAttr}" alt="${alt}" width="${w}" height="${h}" decoding="async" importance="low">`;
    out += '</picture>';
    return out;
  }
  // no manifest: attempt to prefer existing avif/webp same-name files
  const parsed = path.parse(normalized);
  const cand = [];
  try{
    const av = path.join(parsed.dir, parsed.name + '.avif');
    const wp = path.join(parsed.dir, parsed.name + '.webp');
    if (fs.existsSync(path.join(ROOT, av))) cand.push(av);
    if (fs.existsSync(path.join(ROOT, wp))) cand.push(wp);
    if (fs.existsSync(path.join(ROOT, normalized))) cand.push(normalized);
  }catch(e){}
  if (cand.length){
    let out = '<picture>';
    cand.forEach(cf => {
      const ext = (cf.split('.').pop() || '').toLowerCase();
      if (ext === 'avif') out += `<source type="image/avif" srcset="${joinUrl(siteRoot, cf)}">`;
      else if (ext === 'webp') out += `<source type="image/webp" srcset="${joinUrl(siteRoot, cf)}">`;
    });
    out += `<img src="${joinUrl(siteRoot, cand[cand.length-1])}" alt="${alt}" width="${w}" height="${h}" decoding="async" importance="low">`;
    out += '</picture>';
    return out;
  }
  return `<img src="${joinUrl(siteRoot, normalized)}" alt="${alt}" width="${w}" height="${h}" decoding="async" importance="low">`;
}

// attempt to detect a sensible siteUrl fallback from git remote (useful for GH Pages)
const child_process = require('child_process');
function detectSiteUrlFromGit(){
  try{
    const url = String(child_process.execSync('git config --get remote.origin.url', { cwd: ROOT })).trim();
    // match owner/repo from common git URL formats
    const m = url.match(/[:\/]([^\/]+)\/([^\/]+?)(?:\.git)?$/);
    if (m && m[1] && m[2]){
      const owner = m[1];
      const repo = m[2].replace(/\.git$/,'');
      return `https://${owner}.github.io/${repo}`;
    }
  }catch(e){ /* ignore */ }
  return '';
}
const _gitSiteUrl = detectSiteUrlFromGit();
// allow overriding via CLI: --site-root or --siteRoot
function cliOption(name){
  const idx = process.argv.findIndex(a=>a===name);
  if (idx>=0 && process.argv.length>idx+1) return process.argv[idx+1];
  // support --site-root=VALUE
  const match = process.argv.map(a=>{ const m = a.match(/^--site-root=(.*)$/); return m?m[1]:null; }).find(Boolean);
  if (match) return match;
  const match2 = process.argv.map(a=>{ const m = a.match(/^--siteRoot=(.*)$/); return m?m[1]:null; }).find(Boolean);
  if (match2) return match2;
  return null;
}
const cliSiteRoot = cliOption('--site-root') || cliOption('--siteRoot');
// prefer explicit CLI, then ENV_SITE_ROOT if provided (CI / repo variable)
const rawEnvSite = (cliSiteRoot && String(cliSiteRoot).length) ? String(cliSiteRoot) : ((process && process.env && process.env.ENV_SITE_ROOT) ? String(process.env.ENV_SITE_ROOT) : '');
const envSiteRoot = rawEnvSite ? rawEnvSite.replace(/\/+$/,'') : '';
// precompute common injections so per-game SPA copies also contain featured/root content
const siteUrl = (envSiteRoot && envSiteRoot.length) ? envSiteRoot : ((seo && seo.site && seo.site.siteUrl) ? String(seo.site.siteUrl).replace(/\/\/+$/,'') : (_gitSiteUrl || ''));
const rootDescHtml = site && site.description ? `<p style="margin:.5rem 0;color:var(--muted)">${site.description}</p>` : `<p style="margin:.5rem 0;color:var(--muted)">Play Geometry Dash — mobile friendly web builds. No download required.</p>`;
let featuredHtml = '';
if (site && Array.isArray(site.featured)) {
  site.featured.forEach(id => {
    const g = games.find(x=>x.id===id);
    if (!g) return;
    // normalize image path to dist assets location
    let fImg = (g.img && g.img[0]) ? String(g.img[0]).replace(/^\/+/, '') : '';
    if (fImg && !fImg.startsWith('assets/')){
      fImg = fImg.replace(/^games\//, '');
      fImg = 'assets/games/' + fImg;
    }
    featuredHtml += `<div class="game-card-mini" data-id="${g.id}">`;
    // emit responsive picture markup (uses generated manifest when available)
    featuredHtml += renderResponsivePicture(fImg, g.title, 182, 112, siteUrl);
    featuredHtml += `<div class="gmeta"><div class="meta-row"><div class="title">${g.title}</div><div class="publisher">${(typeof g.publisher==='string')?g.publisher:(g.publisher&&g.publisher.name?g.publisher.name:'')}</div></div></div>`;
    featuredHtml += `</div>`;
  });
}

// render per-game SPA copies and also generate index.html from templateHtml with injected content
games.forEach(g=>{
  const dir = path.join(DIST, g.id);
  ensureDir(dir);
  if (templateHtml) {
    // copy the SPA template so the SPA logic loads the correct game from the path
    const outPath = path.join(dir, 'index.html');
    fs.writeFileSync(outPath, templateHtml, 'utf8');

    // Inject per-game SEO: title, description, canonical, and JSON-LD into the copied template
    try{
      let page = fs.readFileSync(outPath,'utf8');
      // determine pageSiteUrl (prefer ENV_SITE_ROOT, then seo.site.siteUrl, then git remote)
      const pageSiteUrl = envSiteRoot || ((seo && seo.site && seo.site.siteUrl) ? seo.site.siteUrl.replace(/\/\/+$/,'') : (_gitSiteUrl || ''));
      const titleTpl = seo && seo.perGameTemplate && seo.perGameTemplate.title ? seo.perGameTemplate.title : '%s — Play Online';
      const descTpl = seo && seo.perGameTemplate && seo.perGameTemplate.description ? seo.perGameTemplate.description : 'Play %s in your browser. No download required.';
      const canonicalTpl = seo && seo.perGameTemplate && seo.perGameTemplate.canonicalTemplate ? seo.perGameTemplate.canonicalTemplate : '%s/%s/';

      const metaTitle = titleTpl.replace('%s', g.title);
      // prefer QA-generated rewrite suggestion when available
      const suggestion = rewriteSuggestions && rewriteSuggestions[g.id] ? String(rewriteSuggestions[g.id]) : null;
      const metaDesc = suggestion ? suggestion : descTpl.replace('%s', g.title);
      const canonicalUrl = (pageSiteUrl && canonicalTpl.indexOf('%s')>=0) ? canonicalTpl.replace('%s', pageSiteUrl).replace('%s', g.id) : (pageSiteUrl ? pageSiteUrl + '/' + g.id + '/' : '/' + g.id + '/');

      // replace <title>
      if (/<title>[\s\S]*?<\/title>/i.test(page)){
        page = page.replace(/<title>[\s\S]*?<\/title>/i, `<title>${metaTitle}</title>`);
      } else {
        page = page.replace(/<head([^>]*)>/i, `<head$1>\n  <title>${metaTitle}</title>`);
      }

      // replace meta description and insert keywords + OG/Twitter tags for better sharing
      const safeMetaDesc = String(metaDesc).replace(/"/g, '&quot;');
      const keywordsContent = (g.keywords && Array.isArray(g.keywords) && g.keywords.length) ? g.keywords.join(', ') : '';
      const safeKeywords = String(keywordsContent).replace(/"/g, '&quot;');
      // normalize image path so it points to dist assets (assets/games/...) when building pages
      let imgPath = (g.img && g.img[0]) ? String(g.img[0]).replace(/^\/+/, '') : '';
      if (imgPath && !imgPath.startsWith('assets/')) {
        // many g.img entries are like "img/..." or "games/img/..." — ensure assets path
        imgPath = imgPath.replace(/^games\//, '');
        imgPath = 'assets/games/' + imgPath;
      }
      const siteImage = imgPath ? joinUrl(pageSiteUrl, imgPath) : (seo && seo.site && seo.site.defaultImage ? joinUrl(pageSiteUrl, seo.site.defaultImage) : '');
      const ogTags = `\n  <meta name="keywords" content="${safeKeywords}">\n  <meta property="og:title" content="${metaTitle}">\n  <meta property="og:description" content="${safeMetaDesc}">\n  <meta property="og:image" content="${siteImage}">\n  <meta property="og:url" content="${canonicalUrl}">\n  <meta name="twitter:card" content="summary_large_image">\n  <meta name="twitter:title" content="${metaTitle}">\n  <meta name="twitter:description" content="${safeMetaDesc}">\n  <meta name="twitter:image" content="${siteImage}">`;
      if (/\<meta[^>]*name=['"]description['"][^>]*>/i.test(page)){
        page = page.replace(/\<meta[^>]*name=['"]description['"][^>]*>/i, `<meta name="description" content="${safeMetaDesc}">${ogTags}`);
      } else {
        page = page.replace(/<head([^>]*)>/i, `<head$1>\n  <meta name="description" content="${safeMetaDesc}">${ogTags}`);
      }

      // insert canonical
      if (!/rel=["']canonical["']/.test(page) && canonicalUrl){
        page = page.replace(/<head([^>]*)>/i, `<head$1>\n  <link rel="canonical" href="${canonicalUrl}">`);
      }

      // build JSON-LD for the game (prefer full suggestion in structured data when available)
      const ld = {
        '@context': 'https://schema.org',
        '@type': ['VideoGame','SoftwareApplication'],
        name: g.title,
        url: canonicalUrl,
        description: (suggestion ? suggestion : (g.desc || metaDesc)),
        image: siteImage,
        applicationCategory: 'Game',
        operatingSystem: 'Web',
        author: g.publisher || (seo && seo.site && { '@type':'Organization','name': seo.site.publisher })
      };
      if (g.rating) ld.aggregateRating = g.rating;

      // replace existing JSON-LD script if present
      if (/\<script[^>]*type=["']application\/ld\+json["'][\s\S]*?<\/script>/i.test(page)){
        page = page.replace(/\<script[^>]*type=["']application\/ld\+json["'][\s\S]*?<\/script>/i, `<script type="application/ld+json">${JSON.stringify(ld)}</script>`);
      } else {
        page = page.replace(/<head([^>]*)>/i, `<head$1>\n  <script type="application/ld+json">${JSON.stringify(ld)}</script>`);
      }

      // inject root description and featured games HTML so SPA copy is usable without JS
      // also append per-game guide, vaultCodes, and levels so pages render game info without client fetch
      let perGameHtml = '';
      // prefer the rewrite suggestion as the server-rendered visible guide when available
      if (suggestion) {
        perGameHtml += `<p style="color:var(--muted);margin:6px 0">${suggestion}</p>`;
      } else if (g.guide) {
        perGameHtml += `<p style="color:var(--muted);margin:6px 0">${g.guide}</p>`;
      }
      if (g.vaultCodes && Array.isArray(g.vaultCodes) && g.vaultCodes.length){
        perGameHtml += `<h2 style="margin-top:8px">Vault Codes</h2><p style="color:var(--muted);margin:6px 0">${g.vaultCodes.join(', ')}</p>`;
      }
      if (g.levels && Array.isArray(g.levels) && g.levels.length){
        perGameHtml += `<h2 style="margin-top:8px">Levels</h2><ol style="color:var(--muted);margin:6px 0 0 18px">`;
        g.levels.forEach(l=>{
          const title = l.name || '';
          const guide = l.guide || '';
          perGameHtml += `<li><strong>${title}</strong>${guide ? ': ' + guide : ''}</li>`;
        });
        perGameHtml += `</ol>`;
      }

      // expose the site-only description in #site-desc (hidden) and render
      // a structured root description that is hydration-friendly. We emit
      // separate containers so the client can update only the per-game
      // portion without replacing the site-level HTML (avoids CLS).
      const siteDescHtml = rootDescHtml;
      page = page.replace('<!--ROOT_DESC-->', `<div id="site-desc" style="display:none">${siteDescHtml}</div><div id="root-desc" data-current-game="${g.id}"><div class="root-site-html">${siteDescHtml}</div><div class="root-game-html">${perGameHtml}</div></div>`);
      page = page.replace('<!--FEATURED_GAMES-->', featuredHtml || '');

      // ensure a global repo-base var is defined for runtime navigation (used by SPA)
      // prefer explicit pageSiteUrl (ENV_SITE_ROOT or seo.site.siteUrl) to compute repo base;
      // fall back to simple first-path-segment heuristic when not available
      const repoBaseScript = `\n  <script>\n    (function(){\n      try{\n        var base = '';\n        // try to derive base from configured page site URL injected at build time\n        try{\n          ${pageSiteUrl ? `var __BUILD_TIME_SITE = ${JSON.stringify(pageSiteUrl)};` : `var __BUILD_TIME_SITE = '';`}\n          if(__BUILD_TIME_SITE){\n            try{\n              // only use the build-time site root if the current location matches it;\n              // otherwise fall back to runtime-first-segment or origin root to avoid incorrect redirects when previewing locally.\n              var buildHref = (new URL(__BUILD_TIME_SITE)).href.replace(/\\\/+$/,'') + '/';\n              if (location.href.indexOf(buildHref) === 0 || (location.origin + location.pathname).indexOf(buildHref) === 0){\n                base = (new URL(__BUILD_TIME_SITE)).pathname.replace(/\\\/+$/,'');\n              } else {\n                base = '';\n              }\n            }catch(e){ base = ''; }\n          }\n        }catch(e){}\n        if(!base){\n          try{ const segs = location.pathname.split('/').filter(Boolean); base = segs.length>0?('/'+segs[0]):''; }catch(e){ base = ''; }\n        }\n        // normalise\n        if(base === '/') base = '';\n        window._globalRepoBase = base || '';\n      }catch(e){ window._globalRepoBase = ''; }\n    })();\n  </script>\n`;
      // build preload tags for images: preload the page image and any featured images
      let preloadTags = '';
      let preconnectTag = '';
      try{
        const preloadSet = new Set();
        if (siteImage) preloadSet.add(siteImage);
        if (Array.isArray(site && site.featured)){
          site.featured.forEach(fid => {
            const fg = games.find(x=>x.id===fid);
            if (!fg) return;
            let fImg = (fg.img && fg.img[0]) ? String(fg.img[0]).replace(/^\/+/, '') : '';
            if (fImg && !fImg.startsWith('assets/')){ fImg = fImg.replace(/^games\//,''); fImg = 'assets/games/' + fImg; }
            if (fImg){
              // prefer to preload available optimized formats (avif/webp) if present
              try{
                const parsed = path.parse(fImg);
                const avif = path.join(parsed.dir, parsed.name + '.avif');
                const webp = path.join(parsed.dir, parsed.name + '.webp');
                if (fs.existsSync(path.join(ROOT, avif))) preloadSet.add(joinUrl(pageSiteUrl, avif));
                if (fs.existsSync(path.join(ROOT, webp))) preloadSet.add(joinUrl(pageSiteUrl, webp));
              }catch(e){}
              preloadSet.add(joinUrl(pageSiteUrl, fImg));
            }
          });
        }
        preloadTags = Array.from(preloadSet).map(u=>`  <link rel="preload" as="image" href="${u}">`).join('\n') + '\n';
        try{ if (pageSiteUrl){ const o = (new URL(pageSiteUrl)).origin; preconnectTag = `  <link rel="preconnect" href="${o}">\n`; } }catch(e){}
      }catch(e){ preloadTags = ''; }

      const siteRootScript = `\n  <script>window._globalSiteRoot = ${JSON.stringify(pageSiteUrl || '')};</script>\n`;
      // service worker registration snippet: try safe candidates in order
      // 1) build-time site root (only if same-origin at runtime), 2) absolute root '/sw.js',
      // 3) repo base '/<repo>/sw.js', 4) relative 'sw.js'
      const swRegister = `\n  <script>\n  (function(){\n    try{\n      if('serviceWorker' in navigator){\n        (async function(){\n          var candidates = [];\n           try{ if(window._globalSiteRoot){ try{ var s = String(window._globalSiteRoot); while(s && s.endsWith('/')) s = s.slice(0,-1); candidates.push(new URL('/sw.js', s).href); }catch(e){} } }catch(e){}\n         try{ if(window._globalRepoBase) candidates.push((window._globalRepoBase||'') + '/sw.js'); }catch(e){}\n\n          for(var i=0;i<candidates.length;i++){\n            var p = candidates[i];\n            try{\n              // attempt registration; stop at first success\n              await navigator.serviceWorker.register(p);\n              console.log('service worker registered', p);\n              break;\n            }catch(err){\n              console.warn('sw register failed for', p, err);\n            }\n          }\n        })();\n      }\n    }catch(e){}\n  })();\n  </script>\n`;
      if (/ <\/head>/i.test(page)){
        page = page.replace(/<\/head>/i, repoBaseScript + preconnectTag + preloadTags + siteRootScript + swRegister + '</head>');
      } else {
        page = repoBaseScript + preconnectTag + preloadTags + siteRootScript + swRegister + page;
      }

      fs.writeFileSync(outPath, page, 'utf8');
    }catch(e){ console.warn('failed to inject SEO into', outPath, e); }

  } else {
    const html = `<!doctype html>\n<html lang="en">\n<head>\n  <meta charset="utf-8" />\n  <meta name="viewport" content="width=device-width,initial-scale=1" />\n  <title>${g.title} — Play Online</title>\n  <meta name="description" content="${g.desc}" />\n  <link rel="stylesheet" href="/index.html">\n</head>\n<body>\n  <div style="padding:18px;max-width:980px;margin:0 auto;font-family:Inter,system-ui"> \n    <a href="/">&larr; Back</a>\n    <h1>${g.title}</h1>\n    <div style="width:100%;max-width:960px;height:480px;background:#000;border-radius:8px;overflow:hidden">\n      <iframe src="${g.embedUrl}" title="${g.title}" sandbox="allow-scripts allow-same-origin allow-popups" allow="autoplay; fullscreen" style="width:100%;height:100%;border:0"></iframe>\n    </div>\n    <p style="color:#666;margin-top:12px">${g.desc}</p>\n  </div>\n</body>\n</html>`;
    fs.writeFileSync(path.join(dir, 'index.html'), html, 'utf8');
  }
  console.log('Generated', g.id);
});

// Build homepage (index.html) with site injection when templateHtml available
if (templateHtml) {
  let indexHtml = templateHtml;
  // homepage template uses runtime lookup for data/games.json — no replacement needed

  // inject root description: emit hydration-friendly containers so client
  // can populate per-game content without clobbering the site-level HTML.
  // To avoid layout shifts we pre-render the first game's per-game HTML on
  // the homepage so the `.meta` area does not change height after JS runs.
  const rootDescHtml = site && site.description ? `<p style="margin:.5rem 0;color:var(--muted)">${site.description}</p>` : `<p style="margin:.5rem 0;color:var(--muted)">Play Geometry Dash — mobile friendly web builds. No download required.</p>`;
  // build per-game HTML for the first game (if present) so homepage has
  // stable content in the `.root-game-html` container immediately.
  let indexPerGameHtml = '';
  try{
    if (Array.isArray(games) && games.length > 0) {
      const first = games[0];
      const suggestionFirst = rewriteSuggestions && rewriteSuggestions[first.id] ? String(rewriteSuggestions[first.id]) : null;
      if (suggestionFirst) indexPerGameHtml += `<p style="color:var(--muted);margin:6px 0">${suggestionFirst}</p>`;
      else if (first.guide) indexPerGameHtml += `<p style="color:var(--muted);margin:6px 0">${first.guide}</p>`;
      if (first.vaultCodes && Array.isArray(first.vaultCodes) && first.vaultCodes.length){
        indexPerGameHtml += `<h2 style="margin-top:8px">Vault Codes</h2><p style="color:var(--muted);margin:6px 0">${first.vaultCodes.join(', ')}</p>`;
      }
      if (first.levels && Array.isArray(first.levels) && first.levels.length){
        indexPerGameHtml += `<h2 style="margin-top:8px">Levels</h2><ol style="color:var(--muted);margin:6px 0 0 18px">`;
        first.levels.forEach(l=>{
          const title = l.name || '';
          const guide = l.guide || '';
          indexPerGameHtml += `<li><strong>${title}</strong>${guide ? ': ' + guide : ''}</li>`;
        });
        indexPerGameHtml += `</ol>`;
      }
    }
  }catch(e){ /* ignore errors building index per-game html */ }
  indexHtml = indexHtml.replace('<!--ROOT_DESC-->', `<div id="root-desc" data-current-game="${(games && games[0] && games[0].id) ? games[0].id : ''}"><div class="root-site-html">${rootDescHtml}</div><div class="root-game-html">${indexPerGameHtml}</div></div>`);

  // inject full games grid: render server-side cards for all games so homepage
  // does not rely on client-side patching to show the complete list.
  let featuredHtml = '';
  games.forEach(g => {
    // normalize image path to dist assets location
    let imgPath = (g.img && g.img[0]) ? String(g.img[0]).replace(/^\/+/, '') : '';
    if (imgPath && !imgPath.startsWith('assets/')){ imgPath = imgPath.replace(/^games\//, ''); imgPath = 'assets/games/' + imgPath; }
    featuredHtml += `<div class="game-card-mini" data-id="${g.id}">`;
    featuredHtml += renderResponsivePicture(imgPath, g.title, 182, 112, siteUrl);
    featuredHtml += `<div class="gmeta"><div class="meta-row"><div class="title">${g.title}</div><div class="publisher">${(typeof g.publisher==='string')?g.publisher:(g.publisher&&g.publisher.name?g.publisher.name:'')}</div></div></div>`;
    featuredHtml += `</div>`;
  });
  indexHtml = indexHtml.replace('<!--FEATURED_GAMES-->', featuredHtml || '');

  // inject global repo base into homepage as well so SPA code can reference it
    const repoBaseScriptHome = `\n  <script>\n    (function(){\n      try{\n        var base = '';\n        try{\n          ${siteUrl ? `var __BUILD_TIME_SITE = ${JSON.stringify(siteUrl)};` : `var __BUILD_TIME_SITE = '';`}\n          if(__BUILD_TIME_SITE){\n            try{\n              var buildHref = (new URL(__BUILD_TIME_SITE)).href.replace(/\\\/+$/,'') + '/';\n              if (location.href.indexOf(buildHref) === 0 || (location.origin + location.pathname).indexOf(buildHref) === 0){\n                base = (new URL(__BUILD_TIME_SITE)).pathname.replace(/\\\/+$/,'');\n              } else {\n                base = '';\n              }\n            }catch(e){ base = ''; }\n          }\n        }catch(e){}\n        if(!base){ try{ const segs = location.pathname.split('/').filter(Boolean); base = segs.length>0?('/'+segs[0]):''; }catch(e){ base = ''; } }\n        if(base === '/') base = '';\n        window._globalRepoBase = base || '';\n      }catch(e){ window._globalRepoBase = ''; }\n    })();\n  </script>\n`;
  if (/<\/head>/i.test(indexHtml)){
    // preload featured images on homepage to warm the browser cache and
    // avoid redundant downloads when navigating to per-game pages.
    let preloadHome = '';
    try{
      const setHome = new Set();
      if (site && Array.isArray(site.featured)){
        site.featured.forEach(id => {
          const g = games.find(x=>x.id===id);
          if (!g) return;
          let imgPath = (g.img && g.img[0]) ? String(g.img[0]).replace(/^\/+/, '') : '';
          if (imgPath && !imgPath.startsWith('assets/')){ imgPath = imgPath.replace(/^games\//,''); imgPath = 'assets/games/' + imgPath; }
          if (imgPath) setHome.add(joinUrl(siteUrl, imgPath));
        });
      }
      preloadHome = Array.from(setHome).map(u=>`  <link rel="preload" as="image" href="${u}">`).join('\n') + '\n';
    }catch(e){ preloadHome = ''; }
    const siteRootScriptHome = `\n  <script>window._globalSiteRoot = ${JSON.stringify(siteUrl || '')};</script>\n`;
    const swRegisterHome = `\n  <script>\n  (function(){\n    try{\n      if('serviceWorker' in navigator){\n        (async function(){\n          var candidates = [];\n          try{ if(window._globalSiteRoot){ try{ var s = String(window._globalSiteRoot); while(s && s.endsWith('/')) s = s.slice(0,-1); candidates.push(new URL('/sw.js', s).href); }catch(e){} } }catch(e){}\n          try{ if(window._globalRepoBase) candidates.push((window._globalRepoBase||'') + '/sw.js'); }catch(e){}\n\n          for(var i=0;i<candidates.length;i++){\n            var p = candidates[i];\n            try{\n              await navigator.serviceWorker.register(p);\n              console.log('service worker registered', p);\n              break;\n            }catch(err){\n              console.warn('sw register failed for', p, err);\n            }\n          }\n        })();\n      }\n    }catch(e){}\n  })();\n  </script>\n`;
    indexHtml = indexHtml.replace(/<\/head>/i, repoBaseScriptHome + preloadHome + siteRootScriptHome + swRegisterHome + '</head>');
  } else {
    const siteRootScriptHome = `\n  <script>window._globalSiteRoot = ${JSON.stringify(siteUrl || '')};</script>\n`;
    indexHtml = repoBaseScriptHome + preloadHome + siteRootScriptHome + indexHtml;
  }

  fs.writeFileSync(path.join(DIST, 'index.html'), indexHtml, 'utf8');
  console.log('Generated index.html');
}

// Write a small service worker to `dist/sw.js` that caches images under assets/games/img
try{
  const swContent = `// Service Worker: simple cache-first strategy for images
const CACHE_NAME = 'h5games-images-v1';
self.addEventListener('install', event => { self.skipWaiting(); });
self.addEventListener('activate', event => { event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k))))); self.clients.claim(); });
self.addEventListener('fetch', event => {
  try{
    const req = event.request;
    const url = new URL(req.url);
    if (req.destination === 'image' || url.pathname.indexOf('/assets/games/img/') !== -1) {
      event.respondWith(caches.open(CACHE_NAME).then(cache => cache.match(req).then(resp => resp || fetch(req).then(networkResp => { try{ cache.put(req, networkResp.clone()); }catch(e){} return networkResp; }))));
    }
  }catch(e){}
});
`;
  fs.writeFileSync(path.join(DIST, 'sw.js'), swContent, 'utf8');
  console.log('Wrote service worker to dist/sw.js');
}catch(e){ console.warn('failed to write sw.js to dist', e); }

// Ensure robots.txt is available at site root in the generated `dist/` output.
try{
  const ROBOTS_SRC = path.join(ROOT, 'robots.txt');
  const ROBOTS_DEST = path.join(DIST, 'robots.txt');
  if (fs.existsSync(ROBOTS_SRC)){
    fs.copyFileSync(ROBOTS_SRC, ROBOTS_DEST);
    console.log('Copied robots.txt to dist/robots.txt');
  } else if (seo && seo.robots) {
    // use seo.robots as fallback; make relative sitemap absolute when siteUrl known
    let robotsText = String(seo.robots || 'User-agent: *\nDisallow:');
    try{
      if (siteUrl && /Sitemap:\s*\//i.test(robotsText)){
        robotsText = robotsText.replace(/Sitemap:\s*\/(\S*)/i, `Sitemap: ${siteUrl.replace(/\/+$/,'')}/$1`);
      }
    }catch(e){}
    fs.writeFileSync(ROBOTS_DEST, robotsText, 'utf8');
    console.log('Wrote robots.txt to dist/robots.txt from seo.json');
  }
}catch(e){ console.warn('failed to write robots.txt to dist', e); }

console.log('All pages generated.');
